{'default': True,
    'config_location': '.',
    'display_options': True,
    'clear_directory': False,
    'project_name': 'gayshit',
    'project_version': '0.01alpha',
    'project_description': 'project_descriptions',
    'author_name': 'Ratin Kumar',
    'author_email': 'placeholder.com',
    'github_username': 'DumbMachine',
    'license': 'MIT',
    'files': {'license': 'MIT',
              'git': True,
              'color': True,
              'requirements': True,
              'tests': True,
              'main': True,
              'contributing': True,
              'interactive': False,
              'manifest': False,
              'setup_cfg': False,
              'setup_py': True,
              'dockerfile': False,
              'readme': 'markdown'},
    'shields': {'base': ['chat',
                         'build',
                         'custom',
                         'license'],
                'entity': ['discord',
                           'appveyor',
                           'custom',
                           'github']}}
The options chosen are as follows:
    {"default": true,
     "config_location": ".",
     "display_options": true,
     "clear_directory": false,
     "project_name": "gayshit",
     "project_version": "0.01alpha",
     "project_description": "project_descriptions",
     "author_name": "Ratin Kumar",
     "author_email": "placeholder.com",
     "github_username": "DumbMachine",
     "license": "MIT",
     "files": {"license": "MIT",
               "git": true,
               "color": true,
               "requirements": true,
               "tests": true,
               "main": true,
               "contributing": true,
               "interactive": false,
               "manifest": false,
               "setup_cfg": false,
               "setup_py": true,
               "dockerfile": false,
               "readme": "markdown"},
     "shields": {"base": ["chat",
                          "build",
                          "custom",
                          "license"],
                 "entity": ["discord",
                            "appveyor",
                            "custom",
                            "github"]}}
